# Data Manipulation Using Numpy

## Different ways of creating Numpy arrays:

In [4]:
import numpy as np
import numpy.char as char

In [3]:
var_1 = np.array([1,2,3,4,5])

In [4]:
print(var_1)

[1 2 3 4 5]


In [6]:
var_2 = np.array([[1,2,3] , [4,5,6]])

In [7]:
print(var_2)

[[1 2 3]
 [4 5 6]]


In [11]:
# array of zero:

np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
# array of one:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# array of random elements:

np.random.seed(4) # its fix the value of randam array , it fix entropy of randam array.
x_1= np.random.rand(4,4) # it pick random no. from 0 to 1 (floting)
print(random)

[[0.96702984 0.54723225 0.97268436 0.71481599]
 [0.69772882 0.2160895  0.97627445 0.00623026]
 [0.25298236 0.43479153 0.77938292 0.19768507]
 [0.86299324 0.98340068 0.16384224 0.59733394]]


In [22]:
 np.random.randn(4,4) # here we add 'n' in end for adding negative no.

array([[ 0.61866969, -0.08798693,  0.4250724 ,  0.33225315],
       [-1.15681626,  0.35099715, -0.60688728,  1.54697933],
       [ 0.72334161,  0.04613557, -0.98299165,  0.05443274],
       [ 0.15989294, -1.20894816,  2.22336022,  0.39429521]])

In [40]:
np.random.seed(9)
X_2=np.random.randint(low=50,high=100,size=(4,4))

# Slicing and Indexing:


In [37]:
x_1[1,1]

np.float64(0.21608949558037638)

In [42]:
X_2[1,2]

np.int32(77)

In [44]:
X_2[1:,2:]

array([[77, 83],
       [50, 96],
       [79, 92]], dtype=int32)

# Manipulation of array:

In [7]:
# creation of identity matrix:

np.identity(3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
b=np.arange(1,13).reshape(3,4)

In [18]:
b=b.ravel()  #it agin change it into 1D.

In [19]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
c=np.arange(1,13).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
c.transpose()  # it transpose the array.

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# Stacking and Splitting of a matrix:

In [27]:
mat_1=np.arange(12).reshape(3,4)
mat_2=np.arange(12, 24).reshape(3,4)

In [28]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
v=np.vstack((mat_1, mat_2)) # it stack up the 2 matrix in vartical form.
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
h=np.hstack((mat_1,mat_2)) # it stack up the 2 matrix in horizontal form.
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [41]:
np.hsplit(v,2) # its split matrix in horizontal form on basis of columns.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [40]:
np.vsplit(h,3) # its split matrix in vertical form on basis of Row.

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]