In [15]:
import numpy as np

## Q1

In [12]:
X=np.arange(0,16).reshape(4,4)

In [13]:
# 1) 
print(X[0:2,0:2])

[[0 1]
 [4 5]]


In [14]:
# 2) 
print(X[2:0,2:0])

[]


In [16]:
# 3)
print(X[2:0:-1,2:0:-1])

[[10  9]
 [ 6  5]]


## Q2

In [19]:
y=np.arange(0,9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
# a
print(y[0,:],y[1,:],y[2,:])

[0 1 2] [3 4 5] [6 7 8]


In [32]:
# b
print(y[0:,0],y[0:,1],y[:,2])

[0 3 6] [1 4 7] [2 5 8]


## Q3

In [30]:
ar1=np.arange(0,9).reshape(3,3)

In [31]:
ar2=np.arange(10,19).reshape(3,3)

In [37]:
# 1 
#a - rowwise
np.vstack((ar1,ar2)) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
# another way
print(np.concatenate([ar1,ar2],axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [46]:
#b - columnwise
np.hstack((ar1,ar2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [47]:
# another way
print(np.concatenate([ar1,ar2],axis=1))

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


## Q4

In [50]:
N=np.array([3,4,5])

In [51]:
N

array([3, 4, 5])

In [52]:
L=[3,4,5]
L

[3, 4, 5]

In [53]:
# a
L*3

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [54]:
# b
N*3

array([ 9, 12, 15])

In [55]:
# c 
L+L

[3, 4, 5, 3, 4, 5]

In [56]:
# d
N+N

array([ 6,  8, 10])

## Q5

In [58]:
p=np.zeros(6,dtype=int)

In [62]:
p[2]=15

In [63]:
p[4]=25

In [64]:
p

array([ 0,  0, 15,  0, 25,  0])