# NumPy-----> Numericl Python 

------>Array--> An array is the ordered data structure that contains data of similar type.

In [2]:
import numpy as np

In [3]:
array_1=np.array([1,2,3])
print(array_1)

[1 2 3]


In [4]:
array_2=np.array([30,40,50])
print(array_2)

[30 40 50]


In [5]:
Array_3=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(Array_3)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [6]:
np.array([1,2,3,4],dtype="int") # dtype id used for declering datatype in array

array([1, 2, 3, 4])

In [7]:
np.array([1,2,3,4],dtype="complex") 

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [8]:
np.array([1,2,3,4],dtype="float") 

array([1., 2., 3., 4.])

In [9]:
list_1=[10,20,30,40]
print(list_1)

[10, 20, 30, 40]


## What is the major difference between numpy array and  the python list:

In [10]:
array_1

array([1, 2, 3])

In [11]:
array_2

array([30, 40, 50])

In [12]:
array_sum=array_1+array_2
print(array_sum)

[31 42 53]


In [13]:
list_1=[1,2,3]
list_2=[30,40,50]
print(list_1+list_2)  # here it concatenate the list not add like array

[1, 2, 3, 30, 40, 50]


In [14]:
# what we need to to for adding two list .
list_ans=[]
for i,j in zip(list_1,list_2):
    list_ans.append(i+j)
print(list_ans)

[31, 42, 53]


#### ---> **NumPy arrays have a fixed size of array creation, but it is not the case when we talk about lists.**

#### ---> The elements in the NumPy array are all required to be of the same data type.

#### ---> NumPy takes very little time to perform arithmetic activities between arrays, whereas lists take time.

#### ---> A NumPy array takes less space as compared to that of lists.


In [15]:
# how to check the dimension of the array:
array_1.ndim # ndim is keyword for checking it , it means ndim.

1

In [16]:
Array_3.ndim

2

In [17]:
# how  we can check the shape of the matrix:
array_1.shape

(3,)

In [18]:
Array_3.shape

(3, 3)

In [19]:
# how can we check the size of the array:
Array_3.size

9

In [20]:
array_1.size

3

## **Array Attributes:**

In [24]:
a1=np.arange(10).reshape(5,2) # arrange helps us to create same as that of the range function
                 # but  in 1D format
print(a1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [34]:
a2=np.arange(12,dtype="float").reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [35]:
a3=np.arange(11,dtype="complex")
print(a3)

[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j]


In [36]:
a2=a2.astype(np.int64)

In [37]:
a2*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [38]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [43]:
for i in np.nditer(a2):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [44]:
a2>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])